// Copyright 2019 IBM Corporation and others.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
:page-layout: guide
:projectid: collection-eclipse-mp-appsody
:page-duration: 20 minutes
:page-releasedate: 2019-09-13
:page-description: Explore how to use the Eclipse MicroProfile Collection and Appsody CLI to create, run, update, deploy, and deliver cloud native microservices.
:guide-author: Kabanero
:page-tags: ['Java', 'MicroProfile', 'Collection']
:page-guide-category: collections
:page-essential: true
:page-essential-order: 1
:page-permalink: /guides/collection-eclipse-mp-appsody/
:imagesdir: /resources
=  Using the Eclipse MicroProfile Collection with the Appsody CLI

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://kabanero.io/guides/{projectid}.html[website].

Explore how to use the Eclipse MicroProfile Kabanero Collection and Appsody CLI to create, run, update, deploy, and deliver cloud native microservices.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to create and run a simple cloud native microservice. Then, you'll update the microservice that you created and deploy it to Kubernetes or Knative. This will all be done by using the Eclipse MicroProfile Kabanero Collection with the link:https://appsody.dev/docs/using-appsody/cli-commands[Appsody CLI].

Kabanero's Eclipse MicroProfile Collection provides a stack that enables the development and optimization of microservices. Applications are written based on the Eclipse MicroProfile API specifications, and built and run with the link:https://openliberty.io/[Open Liberty] runtime. [INSERT SENTENCE ABOUT TEKTON PIPELINES.]

// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

. link:https://docs.docker.com/install/[Docker] must be installed.
. You must have access to a Kubernetes cluster. If you are using Docker for Desktop, you can enable Kubernetes from the menu by selecting Preferences -> Kubernetes -> Enable Kubernetes.
. link:https://appsody.dev/docs/getting-started/installation[Appsody] must be installed.
. (Optional) If you have an enterprise-specific Kabanero Collection Hub, you need the URL to your index file.

// =================================================================================================
// Getting started
// =================================================================================================

== Getting started

=== Understanding the project layout

It contains a `StarterApplication.java` JAX-RS Application class, a `server.xml` Liberty server configuration, an `index.html` static HTML file, and a `pom.xml` project build file.

=== Adding your index

Add your Kabanero index to the Appsody CLI. The following example uses the public index for Kabanero Version 0.1.2.

First, run the following command to check the existing repositories:
----
appsody repo list
----

You see an output similar to the following example:
----
appsody repo list
NAME        URL
*appsodyhub https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
----

Next, run the following command to add the Kabanero index:
----
appsody repo add kabanero https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
----

Check the existing repositories to see that it was added:
----
appsody repo list
NAME        URL
*appsodyhub https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
kabanero    https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
----

Run the following command to set the Kabanero index to the default:
----
appsody appsody repo set-default kabanero
----

Check the existing repositories to see that it was updated:
----
appsody repo list
NAME        URL
appsodyhub  https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
*kabanero   https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
----

Your Appsody CLI is now configured to use the Kabanero Collections. Next, you need to initialize your project.

=== Initializing your project

First, create a directory that will contain the project:
----
mkdir -p ~/projects/simple-microprofile
cd ~/projects/simple-microprofile
----

Run the following command to initialize the project with the Appsody CLI:
----
appsody init java-microprofile
----

The output from the command varies depending on whether you have an installation of Java and Maven on your system. The following example output is from a system with neither installed:
----
[InitScript] Unable to find any JVMs matching version "(null)".
[InitScript] No Java runtime present, try --request to install.
[InitScript] Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
[InitScript] No Java runtime present, requesting install.
[Warning] The stack init script failed: exit status 1
[Warning] Your local IDE may not build properly, but the Appsody container should still work.
[Warning] To try again, resolve the issue then run `appsody init` with no arguments.
----

Your project is now initialized.

// =================================================================================================
// Running the Appsody development environment
// =================================================================================================

== Running the Appsody development environment

Run the following command to start the Appsody development environment:
----
appsody run
----

The Appsody CLI launches a local docker image that contains an Open Liberty server that hosts the microservice. After some time, you see a message similar to the following example:
----
[Container] [INFO] [AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 20.235 seconds.
----

This message indicates that the server is started and you are ready to begin development.

// =================================================================================================
// Creating and updating the application
// =================================================================================================

== Creating and updating the application

Navigate to the JAX-RS application endpoint to confirm that there are no JAX-RS resources available. Point your browser to the http://localhost:9080/starter URL. You see the following `HTTP 500` error that states that there are no provider or resource classes that are associated with the application:
----
Error 500: javax.servlet.ServletException: At least one provider or resource class should be specified for application class "dev.appsody.starter.StarterApplication
----

Go to the `src/main/java/dev/appsody/starter` directory that's within your project folder. Create a file named `StarterResource.java`. Open the file, populate it with the following code, and save it:
----
package dev.appsody.starter;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
@Path("/resource")
public class StarterResource {
    @GET
    public String getRequest() {
        return "StarterResource response";
    }
}
----

After you save, the source compiles and the application updates. You see messages similar to the following example:
----
[Container] [INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://85862d8696be:9080/
[Container] [INFO] [AUDIT   ] CWWKZ0009I: The application starter-app has stopped successfully.
[Container] [INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://85862d8696be:9080/
[Container] [INFO] [AUDIT   ] CWWKZ0003I: The application starter-app updated in 0.988 seconds.
----

Now if you browse to the http://localhost:9080/starter URL you no longer see the `HTTP 500` error. The resource that you just added is available in the `src/main/java/dev/appsody/starter` directory. Point your browser to the http://localhost:9080/starter/resource URL to see the following resource response:
----
StarterResource response
----

Try changing the message in the `StarterResource.java` file, saving, and refreshing the page. You'll see that it takes only a few seconds for the change to take effect.

//
// =================================================================================================
// Stopping the Appsody development environment
// =================================================================================================
//
// == Stopping the Appsody development environment
// Use `Ctrl-C` to stop the Appsody development environment.

== Deploying to Kubernetes

After you finish writing your application code, the Appsody CLI makes it easy to deploy to a Kubernetes cluster for further testing. Ensure that your `kubectl` command is configured with cluster details, and run the following command to deploy your application:
----
appsody deploy
----

This command builds a new Docker image that is optimized for production deployment and deploys the image to your Kubernetes cluster. After some time you see a message similar to the following example:
----
Deployed project running at http://localhost:30262
----

Run the following command to check the status of the application pods:
----
kubectl get pods
----

After the `simple-microprofile` pod starts, go to the URL that was returned in the previous step, and you see the Appsody microservice splash screen. Go to http://localhost:30262/starter/resource and you see your deployed application response.

Use the following command to stop the deployed application:
----
appsody deploy delete
----

After you run this command, and the deployment is deleted, you see the following message:
----
Deployment deleted
----

// =================================================================================================
// Deploying to Knative
// =================================================================================================

== Deploying to Knative

You can also choose to deploy the application with Knative Serving. To deploy the application with Knative Serving, you must first install Knative in your Kubernetes cluster. For information about installing Knative, see the link:https://knative.dev/docs/install/[Knative documentation]. When Knative is installed, run the following command to generate an `app-deploy.yaml` file:
----
appsody deploy —generate-only
----

Open the `app-deploy.yaml` file that you generated and add the following information to the spec definition:
----
createKnativeService: true
----

Run the following command to deploy the application from your local image registry:
----
appsody deploy --tag dev.local/simple-microprofile --namespace <namespace>
----

Alternatively, run the following command to deploy the application from Docker Hub:
----
appsody deploy --push -—tag <my-account>/simple-microprofile --namespace <namespace>
----

After the application deploys, you see a message similar to the following example that details the serving URL:
----
Deployed project running at "http://simple-microprofile.knative-serving.192.168.1.10.nip.io"
----

To see the response from your application, point your browser to the http://simple-microprofile.knative-serving.192.168.1.10.nip.io/starter/resource URL.

// =================================================================================================
// Delivering to enterprise pipelines
// =================================================================================================

== Delivering to enterprise pipelines

After you develop and test your application, it's time to deliver it to your enterprise Kabanero pipelines. To deliver it to the pipelines, push the project to a pre-configured Git repository. This repository can be public or enterprise. Your operations team configures the webhooks on the repository that trigger the pipelines. For more information about configuring webhooks for Tekton, see link:www...[David's topic].

== Nice work!
